import { readFile, writeFile } from "node:fs/promises";
import { badgeDesignSchema } from "../packages/design/src/badge-design";
const file = new URL("../packages/design/src/catalog.json", import.meta.url);
const catalog = JSON.parse(await readFile(file, "utf8"));
const text = (
	id: string,
	binding: string,
	value: string,
	x: number,
	y: number,
	w: number,
	h: number,
	size: number,
	color: string,
	extra = {},
) => ({
	id,
	kind: "text",
	binding,
	text: value,
	x,
	y,
	w,
	h,
	size,
	color,
	font: "sans",
	weight: "500",
	align: "left",
	fit: "shrink",
	...extra,
});
const graphic = (
	id: string,
	pattern: string,
	x: number,
	y: number,
	w: number,
	h: number,
	color: string,
	accent = color,
	extra = {},
) => ({
	id,
	kind: "graphic",
	pattern,
	x,
	y,
	w,
	h,
	color,
	accent,
	density: 0.5,
	seed: 42091,
	...extra,
});
const gradient = (
	id: string,
	x: number,
	y: number,
	w: number,
	h: number,
	colors: string[],
	extra = {},
) => ({
	id,
	kind: "gradient",
	x,
	y,
	w,
	h,
	direction: "diagonal",
	stops: colors.map((color, i) => ({ at: i / (colors.length - 1), color })),
	...extra,
});
const palettes = [
	{
		id: "thermal",
		name: "Térmico",
		title: "HEAT SIGNAL",
		subtitle: "A HUMAN FREQUENCY",
		surface: "satin",
		filter: "thermal",
		paper: "#070c2a",
		ink: "#fff3df",
		accent: "#ff7942",
		roughness: 0.45,
		iridescence: 0.08,
		colors: ["#0b1234", "#63226c", "#ff742b"],
	},
	{
		id: "prism",
		name: "Prisma",
		title: "LIVING PRISM",
		subtitle: "EVERY ANGLE, A NEW YOU",
		surface: "prism",
		filter: "original",
		paper: "#dce1ed",
		ink: "#eff4fc",
		accent: "#b8cef7",
		roughness: 0.18,
		iridescence: 0.42,
		colors: ["#d8e4f4", "#e4d9e7", "#fff1dc"],
	},
	{
		id: "chrome",
		name: "Cromo",
		title: "CHROME ARCHIVE",
		subtitle: "CAST IN LIGHT",
		surface: "chrome",
		filter: "silver",
		paper: "#697786",
		ink: "#f3f7fa",
		accent: "#c1d7e6",
		roughness: 0.14,
		iridescence: 0.06,
		colors: ["#dce5ed", "#a4b1be", "#f3f7fa"],
	},
];
for (const [index, p] of palettes.entries()) {
	const thermal = p.id === "thermal";
	const backInk = thermal ? "#fff1df" : "#182837";
	const backAccent = thermal ? "#ff8951" : "#415570";
	const recipe = {
		version: 1,
		promptVersion: "style-director-v1",
		model: "badge-studio-originals",
		name: p.name,
		description: `Material físico ${p.name} con retrato, luz reactiva y reverso editorial.`,
		surface: p.surface,
		finish: "crystal",
		palette: p.colors,
		accent: p.accent,
		portrait: { strength: 0, saturation: 1, contrast: 1 },
		texture: { pattern: "none", amount: 0, scale: 1 },
		material: { roughness: p.roughness, iridescence: p.iridescence },
		motion: { speed: 0.45, amplitude: 0.35 },
		heading: "sans",
		seed: 42091 + index * 519,
	};
	const front = [
		gradient("base-light", 0, 0, 1024, 1536, p.colors),
		{
			id: "hero-portrait",
			kind: "portrait",
			x: 0,
			y: 90,
			w: 1024,
			h: 1446,
			radius: 0,
			filter: p.filter,
			contrast: 1,
			crop: { x: 0.5, y: 0.5, zoom: 1.08 },
			fade: { x: 0.045, top: 0.055, bottom: 0.25 },
		},
		gradient("footer-shade", 0, 1030, 1024, 506, ["#06102600", "#061026bb", "#061026ee"], {
			direction: "vertical",
		}),
		graphic("cross-top-left", "cross", 48, 102, 32, 32, p.accent, p.accent, { opacity: 0.5 }),
		graphic("cross-top-right", "cross", 944, 102, 32, 32, p.accent, p.accent, { opacity: 0.5 }),
		graphic("cross-bottom-left", "cross", 48, 1442, 32, 32, p.accent, p.accent, { opacity: 0.6 }),
		graphic("cross-bottom-right", "cross", 944, 1442, 32, 32, p.accent, p.accent, { opacity: 0.6 }),
		text("name", "name", "", 94, 1170, 836, 142, 104, p.ink, {
			align: "center",
			segment: "first",
			transform: "uppercase",
			tracking: 5,
			weight: "400",
		}),
		text("edition", "event", "", 105, 1318, 814, 54, 27, p.accent, {
			align: "center",
			tracking: 10,
			transform: "uppercase",
		}),
		text("studio", "none", "BADGE STUDIO / ORIGINALS", 106, 1464, 615, 30, 15, p.ink, {
			font: "mono",
			tracking: 2,
		}),
		text("number", "number", "", 767, 1448, 150, 48, 24, p.ink, {
			align: "right",
			prefix: "No. ",
			numberDigits: 3,
			font: "mono",
		}),
	];
	const back = [
		gradient("reverse-light", 0, 0, 1024, 1536, p.colors),
		graphic(
			"reverse-texture",
			thermal ? "terrain" : p.id === "chrome" ? "scanlines" : "path",
			0,
			0,
			1024,
			1536,
			backAccent,
			p.accent,
			{
				opacity: thermal ? 0.3 : 0.09,
				...(p.id === "prism"
					? { path: "M0 100 L1024 820 L140 1536 M140 0 L980 1460 M0 1000 L1024 240", stroke: 3 }
					: {}),
			},
		),
		text("index", "none", `MATERIAL STUDY / 00${index + 1}`, 72, 118, 880, 42, 21, backAccent, {
			font: "mono",
			tracking: 4,
		}),
		text("headline", "none", p.title, 70, 220, 884, 150, p.id === "chrome" ? 100 : 124, backInk, {
			weight: "700",
			tracking: -6,
			font: p.id === "prism" ? "serif" : "sans",
		}),
		text("subtitle", "none", p.subtitle, 74, 374, 876, 55, 22, backAccent, {
			tracking: 6,
			font: "mono",
		}),
		{
			id: "portrait-detail",
			kind: "portrait",
			x: 76,
			y: 490,
			w: 220,
			h: 280,
			radius: p.id === "prism" ? 100 : 8,
			filter: p.filter,
			crop: { x: 0.5, y: 0.45, zoom: 1.3 },
			contrast: 1,
		},
		text("reverse-name", "name", "", 342, 505, 596, 128, 69, backInk, {
			weight: "600",
			font: p.id === "prism" ? "serif" : "sans",
			tracking: -2,
		}),
		text("role", "role", "", 344, 665, 590, 50, 24, backAccent, {
			transform: "uppercase",
			tracking: 5,
			font: "mono",
		}),
		text("organization", "organization", "", 344, 726, 590, 50, 24, backInk),
		{
			id: "divider",
			kind: "shape",
			shape: "line",
			x: 76,
			y: 848,
			w: 872,
			h: 2,
			color: backAccent,
			opacity: 0.35,
			radius: 0,
			stroke: 1,
		},
		text("access-label", "none", "YOUR WAY IN", 76, 900, 650, 56, 26, backAccent, {
			font: "mono",
			tracking: 4,
		}),
		text("edition-reverse", "event", "", 76, 992, 470, 130, 40, backInk, {
			font: p.id === "prism" ? "serif" : "sans",
			tracking: -1,
		}),
		text("serial-label", "none", "UNIQUE TO YOU", 76, 1180, 470, 44, 19, backAccent, {
			font: "mono",
			tracking: 3,
		}),
		text("serial", "signature", "", 76, 1240, 470, 56, 29, backInk, { font: "mono", tracking: 4 }),
		text("reverse-footer", "none", "BADGE STUDIO / ORIGINALS", 76, 1435, 630, 40, 17, backAccent, {
			font: "mono",
			tracking: 3,
		}),
		text("reverse-number", "number", "", 766, 1418, 184, 65, 39, backInk, {
			font: "mono",
			align: "right",
			prefix: "No. ",
			numberDigits: 3,
		}),
		{
			id: "access-qr",
			kind: "qr",
			x: 602,
			y: 980,
			w: 336,
			h: 336,
			foreground: "#101b2c",
			background: "#fffaf0",
		},
	];
	const design = badgeDesignSchema.parse({
		version: 1,
		source: p.id,
		name: p.name,
		description: recipe.description,
		event: p.title,
		artPrompt: "",
		material: {
			surface: p.surface,
			roughness: p.roughness,
			iridescence: p.iridescence,
			speed: 0.45,
			focus: { x: 0.5, y: 0.47, radius: 0.29 },
			recipe,
		},
		front: { background: p.paper, layers: front },
		back: { background: p.paper, layers: back },
	});
	const existing = catalog.findIndex((item: { source: string }) => item.source === p.id);
	if (existing >= 0) catalog[existing] = design;
	else catalog.push(design);
}
await writeFile(file, `${JSON.stringify(catalog, null, 2)}\n`);
console.log("Added three validated, editable material originals.");
